/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NouvelleSimulationRouteImport } from './routes/nouvelle-simulation'
import { Route as MonAbonnementRouteImport } from './routes/mon-abonnement'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlanReferenceRouteImport } from './routes/plan.$reference'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as AdminAbonnementsRouteImport } from './routes/admin.abonnements'
import { Route as AdminUtilisateursIndexRouteImport } from './routes/admin.utilisateurs.index'
import { Route as AdminUtilisateursIdRouteImport } from './routes/admin.utilisateurs.$id'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NouvelleSimulationRoute = NouvelleSimulationRouteImport.update({
  id: '/nouvelle-simulation',
  path: '/nouvelle-simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const MonAbonnementRoute = MonAbonnementRouteImport.update({
  id: '/mon-abonnement',
  path: '/mon-abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlanReferenceRoute = PlanReferenceRouteImport.update({
  id: '/plan/$reference',
  path: '/plan/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbonnementsRoute = AdminAbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtilisateursIndexRoute = AdminUtilisateursIndexRouteImport.update({
  id: '/utilisateurs/',
  path: '/utilisateurs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtilisateursIdRoute = AdminUtilisateursIdRouteImport.update({
  id: '/utilisateurs/$id',
  path: '/utilisateurs/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/nouvelle-simulation': typeof NouvelleSimulationRoute
  '/parametres': typeof ParametresRoute
  '/simulations': typeof SimulationsRoute
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/plan/$reference': typeof PlanReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/utilisateurs/$id': typeof AdminUtilisateursIdRoute
  '/admin/utilisateurs/': typeof AdminUtilisateursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/nouvelle-simulation': typeof NouvelleSimulationRoute
  '/parametres': typeof ParametresRoute
  '/simulations': typeof SimulationsRoute
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/plan/$reference': typeof PlanReferenceRoute
  '/admin': typeof AdminIndexRoute
  '/admin/utilisateurs/$id': typeof AdminUtilisateursIdRoute
  '/admin/utilisateurs': typeof AdminUtilisateursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/nouvelle-simulation': typeof NouvelleSimulationRoute
  '/parametres': typeof ParametresRoute
  '/simulations': typeof SimulationsRoute
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/plan/$reference': typeof PlanReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/utilisateurs/$id': typeof AdminUtilisateursIdRoute
  '/admin/utilisateurs/': typeof AdminUtilisateursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connexion'
    | '/mon-abonnement'
    | '/nouvelle-simulation'
    | '/parametres'
    | '/simulations'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/paiements'
    | '/plan/$reference'
    | '/admin/'
    | '/admin/utilisateurs/$id'
    | '/admin/utilisateurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/mon-abonnement'
    | '/nouvelle-simulation'
    | '/parametres'
    | '/simulations'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/paiements'
    | '/plan/$reference'
    | '/admin'
    | '/admin/utilisateurs/$id'
    | '/admin/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connexion'
    | '/mon-abonnement'
    | '/nouvelle-simulation'
    | '/parametres'
    | '/simulations'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/paiements'
    | '/plan/$reference'
    | '/admin/'
    | '/admin/utilisateurs/$id'
    | '/admin/utilisateurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  MonAbonnementRoute: typeof MonAbonnementRoute
  NouvelleSimulationRoute: typeof NouvelleSimulationRoute
  ParametresRoute: typeof ParametresRoute
  SimulationsRoute: typeof SimulationsRoute
  TarifsRoute: typeof TarifsRoute
  PlanReferenceRoute: typeof PlanReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouvelle-simulation': {
      id: '/nouvelle-simulation'
      path: '/nouvelle-simulation'
      fullPath: '/nouvelle-simulation'
      preLoaderRoute: typeof NouvelleSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-abonnement': {
      id: '/mon-abonnement'
      path: '/mon-abonnement'
      fullPath: '/mon-abonnement'
      preLoaderRoute: typeof MonAbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/plan/$reference': {
      id: '/plan/$reference'
      path: '/plan/$reference'
      fullPath: '/plan/$reference'
      preLoaderRoute: typeof PlanReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abonnements': {
      id: '/admin/abonnements'
      path: '/abonnements'
      fullPath: '/admin/abonnements'
      preLoaderRoute: typeof AdminAbonnementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utilisateurs/': {
      id: '/admin/utilisateurs/'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs/'
      preLoaderRoute: typeof AdminUtilisateursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utilisateurs/$id': {
      id: '/admin/utilisateurs/$id'
      path: '/utilisateurs/$id'
      fullPath: '/admin/utilisateurs/$id'
      preLoaderRoute: typeof AdminUtilisateursIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbonnementsRoute: typeof AdminAbonnementsRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUtilisateursIdRoute: typeof AdminUtilisateursIdRoute
  AdminUtilisateursIndexRoute: typeof AdminUtilisateursIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbonnementsRoute: AdminAbonnementsRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUtilisateursIdRoute: AdminUtilisateursIdRoute,
  AdminUtilisateursIndexRoute: AdminUtilisateursIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  MonAbonnementRoute: MonAbonnementRoute,
  NouvelleSimulationRoute: NouvelleSimulationRoute,
  ParametresRoute: ParametresRoute,
  SimulationsRoute: SimulationsRoute,
  TarifsRoute: TarifsRoute,
  PlanReferenceRoute: PlanReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
